INSERT INTO job_offer (job_offer_title, description, employer_id, tech_specialization, work_type, city, experience, salary)
VALUES
    ('Java Developer', 'Develop and maintain Java applications.', 1, 'BACKEND', 'REMOTE', 'WARSZAWA', 'MID', 'PLN_5000_8000'),
    ('Frontend Developer', 'Build and optimize frontend applications.', 2, 'FRONTEND', 'ONSITE', 'KRAKÓW', 'JUNIOR', 'PLN_3000_5000'),
    ('Backend Developer', 'Design and develop backend services in Java and KOTLIN.', 1, 'BACKEND', 'REMOTE', 'WARSZAWA', 'MID', 'PLN_5000_8000'),
    ('Fullstack Developer', 'Build and maintain both frontend and backend parts of the application.', 2, 'FULLSTACK', 'HYBRID', 'KRAKÓW', 'SENIOR', 'PLN_8000_12000'),
    ('Python Developer', 'Write and optimize Python code for data processing and machine learning.', 3, 'BACKEND', 'ONSITE', 'WROCŁAW', 'JUNIOR', 'PLN_3000_5000'),
    ('Frontend Developer', 'Create engaging user interfaces using React and TypeScript.', 4, 'FRONTEND', 'REMOTE', 'POZNAŃ', 'MID', 'PLN_5000_8000'),
    ('DevOps Engineer', 'Configure and maintain cloud infrastructure with CI/CD pipelines.', 1, 'BACKEND', 'REMOTE', 'WARSZAWA', 'SENIOR', 'PLN_8000_12000'),
    ('QA Engineer', 'Test and ensure quality for Java-based applications and services.', 1, 'BACKEND', 'HYBRID', 'WARSZAWA', 'MID', 'PLN_5000_8000'),
    ('Cloud Engineer', 'Work with cloud technologies to build scalable systems.', 2, 'BACKEND', 'ONSITE', 'KRAKÓW', 'MID', 'PLN_5000_8000'),
    ('Business Analyst', 'Analyze business requirements and communicate with development teams.', 2, 'FRONTEND', 'REMOTE', 'KRAKÓW', 'JUNIOR', 'PLN_3000_5000'),
    ('iOS Developer', 'Develop and maintain iOS applications.', 3, 'BACKEND', 'REMOTE', 'WROCŁAW', 'SENIOR', 'PLN_8000_12000'),
    ('Android Developer', 'Build Android applications with Kotlin and Java.', 3, 'BACKEND', 'HYBRID', 'WROCŁAW', 'MID', 'PLN_5000_8000'),
    ('Game Developer', 'Develop mobile and desktop games using Unity.', 4, 'FULLSTACK', 'ONSITE', 'POZNAŃ', 'MID', 'PLN_5000_8000'),
    ('UI/UX Designer', 'Design user interfaces and experiences for web applications.', 4, 'FRONTEND', 'HYBRID', 'POZNAŃ', 'JUNIOR', 'PLN_3000_5000');


INSERT INTO job_offer_must_have_skills (job_offer_id, must_have_skills)
VALUES
    (1, 'JAVA'),
    (1, 'SPRING_BOOT'),
    (2, 'HTML'),
    (2, 'CSS'),
    (2, 'REACT'),
    (3, 'PYTHON'),
    (3, 'REACT'),
    (4, 'REACT'),
    (4, 'TYPE_SCRIPT'),
    (4, 'CSS'),
    (5, 'JAVA_SCRIPT'),
    (5, 'REACT'),
    (6, 'JAVA'),
    (6, 'KOTLIN'),
    (6, 'SPRING_BOOT'),
    (7, 'DOCKER'),
    (8, 'JAVA'),
    (8, 'JUNIT'),
    (9, 'PYTHON'),
    (9, 'LINUX'),
    (10, 'KAFKA'),
    (11, 'JAVA'),
    (11, 'KOTLIN'),
    (11, 'MICROSERVICES'),
    (12, 'KOTLIN'),
    (12, 'JAVA'),
    (13, 'MICROSERVICES'),
    (13, 'DOCKER'),
    (13, 'GIT'),
    (13, 'REST_API'),
    (14, 'HTML'),
    (14, 'CSS'),
    (14, 'REACT');

INSERT INTO job_offer_nice_to_have_skills (job_offer_id, nice_to_have_skills)
VALUES
    (1, 'DOCKER'),
    (2, 'JAVA_SCRIPT'),
    (3, 'DOCKER'),
    (4, 'GIT'),
    (5, 'TYPE_SCRIPT'),
    (6, 'MICROSERVICES'),
    (6, 'KAFKA'),
    (7, 'GIT'),
    (8, 'GIT'),
    (9, 'DOCKER'),
    (10, 'DOCKER'),
    (11, 'GIT'),
    (11, 'REST_API'),
    (12, 'REST_API'),
    (12, 'GIT'),
    (13, 'KAFKA'),
    (13, 'JAVA'),
    (14, 'VISUAL_STUDIO_CODE'),
    (14, 'ANGULAR'),
    (14, 'TYPE_SCRIPT');


